add missing -lcrypto
was saying:
```
061240 ~/w/f/bocla (master) $ make clean s
make -C tmp/ clean NAME=bocla
make[1]: Entering directory '/home/jmettraux/w/f/bocla/tmp'
rm -f *.o
rm -f *.so
rm -f *.c
rm -f s
make[1]: Leaving directory '/home/jmettraux/w/f/bocla/tmp'
make -C tmp/ s NAME=bocla
make[1]: Entering directory '/home/jmettraux/w/f/bocla/tmp'
../../rodzo/bin/rodzo ../spec -o s.c
. processing ../spec/bocla_spec.c
. processing ../spec/s3_spec.c
. processing ../spec/sig4_spec.c
. wrote s.c
c99 -I../src -g -Wall   -c -o flutim.o ../src/flutim.c
c99 -I../src -g -Wall   -c -o bocla.o ../src/bocla.c
c99 -I../src -g -Wall   -c -o bocla_s3.o ../src/bocla_s3.c
c99 -I../src -g -Wall   -c -o flutil.o ../src/flutil.c
c99 -I../src -g -Wall   -c -o bocla_sig4.o ../src/bocla_sig4.c
c99 -I../src -g -Wall  -lcurl  s.c flutim.o bocla.o bocla_s3.o flutil.o bocla_sig4.o   -o s
/usr/bin/ld: bocla_sig4.o: undefined reference to symbol 'EVP_sha256@@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 's' failed
make[1]: *** [s] Error 1
make[1]: Leaving directory '/home/jmettraux/w/f/bocla/tmp'
Makefile:7: recipe for target 's' failed
make: *** [s] Error 2
```